import type { Metadata } from "next";
import {Inter, Mulish, Sora, SUSE} from "next/font/google";
import "./styles/globals.css";


const inter=Inter({
    weight:["200", "300","400", "500","700"],
    subsets: ["latin"],
});
const suse = SUSE({

    weight:["200", "300","400", "500","700"],
  subsets: ["latin"],
});
const sora = Sora({

    weight:["200", "300","400", "500","700"],
  subsets: ["latin"],
});
const mulish = Mulish({

    weight:["200", "300","400", "500","700"],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "E-shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} ${suse.className} ${mulish.className} ${inter.className} antialiased`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
